### PR TITLE
Issue template for `Chain support request`

### LINKED ISSUE #542: Add issue template in github for requesting adding a new chain
The new issue template should be specific to adding new `ChainInfo` provide a list of the information that needs to be provided as well as all the configuration steps required to be performed by the backend team. 

This would be an interim solution, unless we see that it works well.

### PR DESCRIPTION
**Pull request by jpalvarezl**
Closes #542

### CODE REVIEW

**Comment by rmeissner** [comment]
Shouldn't this rather be on the config service?

**Comment by rmeissner** [comment]
Also currently we collect this information via a google doc and then add it via the admin. Do we somewhere define if this would become obsolete? Who do we expect to open such issues?

**Comment by jpalvarezl** [comment]
I saw it as a checklist for myself, as (probably) I would have to add these values in the config service admin panel and then the webhook to the core services. I would just like to have help gathering data about the chain from whoever requests it and a simple checklist to see that I have not forgotten anything "configuration-wise"

**Comment by jpalvarezl** [comment]
this would also provide a history of chains we support in the form of github issues, which I personally see as an advantage (we can always call the `/chains/<chain_id>` endpoint but still.

**Comment by jpalvarezl** [comment]
Transferred: https://github.com/gnosis/safe-config-service/pull/192

**Pull request closed without merging**
