### PR TITLE
Github action migration

### PR DESCRIPTION
**Pull request by jpalvarezl**
Reference #241 

Changes: 
- Added concurrent jobs `rustfmt` and `build` as requirement for merging
- Deployment is still in test face, I put an `echo` instead just to be sure we don't polute docker before we know the setup works
- remove remnants of travis.yml
- Apply the prior configuration of `grcov` to the `action-rs/grcov.yml` file
- cargo deps are cached
- grcov cached

### CODE REVIEW

**Comment by jpalvarezl** [comment]
I was thinking to merge this, I replace the deployment script run with an `echo` just to test this first if you think that's a good idea.

**Comment by rmeissner** [comment]
I would just change the repo setting and remove all traces of travis :D

**Comment by jpalvarezl** [comment]
On the plus side, submission to coveralls works, on the downside (or maybe upside) why the hell we got 5.7% using the same `exlc-*` statements.

**Comment by jpalvarezl** [comment]
Just to document this here. There is `403` being thrown when trying to recover `grcov` from the cache. Not sure what it is associated, but unbeliveable, fetching and building `grcov` is our current build choke point. Cargo cache works like a charm.

**Review by rmeissner — APPROVED** [review]

**Pull request merged**
