### PR TITLE
Update .env.sample

### LINKED ISSUE #386: Update `.env.sample`
The `.env.sample` file is outdated. 

We need to introduce the following changes:

(rename) `ROCKET_LOG` -> `ROCKET_LOG_LEVEL`
(remove)  `ROCKET_DATABASES={service_cache={url="redis://127.0.0.1:6379"}}`
(add) `REDIS_URL="redis://127.0.0.1:6379"` 
(add) `FEATURE_FLAG_NESTED_DECODING=true`

### PR DESCRIPTION
**Pull request by fmrsabino**
Closes #386

- Add `FEATURE_FLAG_NESTED_DECODING` (default value: `true`)
- Add `REDIS_URL` (default value: `redis://127.0.0.1:6379`)
- Remove `ROCKET_DATABASES`

### Open Questions:

Is `ROCKET_LOG_LEVEL` read by Rocket itself? I did not include it here in these changes.

### CODE REVIEW

**Comment by jpalvarezl** [comment]
Yes, it is part of the variables that rocket consumes. It used to be `ROCKET_LOG` but the name go deprecated.

I would prefer to include, we would otherwise get this warning every time we start the service.

**Review by jpalvarezl — APPROVED** [review]
I approve the PR just not to block you, but like said in the other comment, please include `ROCKET_LEVEL_LOG` as well as part of the changes :) I think also the values got changed, what we have on staging is `ROCKET_LEVEL_LOG=normal`

**Comment by fmrsabino** [comment]
> I approve the PR just not to block you, but like said in the other comment, please include `ROCKET_LEVEL_LOG` as well as part of the changes :) I think also the values got changed, what we have on staging is `ROCKET_LEVEL_LOG=normal`

I will update in the context of this PR! 👍

**Comment by fmrsabino** [comment]
Converted to Draft until issue with deployment is fixed

**Pull request merged**
