### PR TITLE
docker compose container image building bug

### PR DESCRIPTION
**Pull request by InoMurko**
My docker compose building process wants to add the .git folder and it breaks docker. I thought I'd share this fix.
Similar setup:
https://github.com/gnosis/safe-transaction-service/blob/master/.dockerignore#L3-L4
https://github.com/gnosis/safe-config-service/blob/main/.dockerignore#L3-L4

### CODE REVIEW

**Comment by InoMurko** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jpalvarezl** [comment]
recheckcla

**Comment by jpalvarezl** [comment]
recheckcla

**Comment by jpalvarezl** [comment]
Our Unit tests are a bit flake-y at the moment.A fix for this is coming in #701. Sorry for the inconvenience 🙏

**Comment by InoMurko** [comment]
recheckcla

**Review by jpalvarezl — APPROVED** [review]

**Comment by fmrsabino** [comment]
recheckcla

**Comment by InoMurko** [comment]
I'm a bit confused how CLA Assistant works 🗡️

**Comment by InoMurko** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by InoMurko** [comment]
recheckcla

**Comment by jpalvarezl** [comment]
We are asking internally how we can address this. I hope I can get back to you with an asnwer really soon. Sorry for the constant rebasing 🙏

**Comment by fmrsabino** [comment]
@InoMurko we have updated the CLA action as we believe that this was caused because of a bug in the action.

Can you try rebasing again the branch? If rebasing fails on the check can you then try to write again `I have read the CLA Document and I hereby sign the CLA`.

Apologies for the inconvenience.

**Pull request merged**
